/**
 * Compile server.ts → server.js at the repo root.
 *
 * server.js is what `npm start` (= `node server.js`) invokes.
 * Bundles server.ts + everything it imports from `@/lib` and friends
 * into a single ESM file (package.json `type: module` makes a plain
 * .js ESM here — no .mjs marker needed); leaves third-party deps
 * external for runtime resolution against the deploy artifact's
 * bundled node_modules/.
 *
 * No NFT trace step — the build assumes the deploy artifact carries
 * every dep `npm ci` installs, wholesale, so there's no minimized
 * tree that needs runtime-deps manifests folded back into Next's
 * standalone tracer. Earlier contracts (CI-tarball + standalone)
 * needed bin/server.trace.json; deploy shapes that ship the full
 * tree don't.
 *
 * Build-time --check smoke validates module-level imports here
 * (cheap pre-check). Real-boot smoke runs in scripts/postbuild.ts
 * against the just-built server.js (catches everything --check
 * doesn't, including the shutdown-handler-bug class).
 */
import { build } from "esbuild";
import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";

const outfile = "server.js";

// Inline SENTRY_RELEASE at build time so events from the server
// runtime carry the right release tag even when prod's env file
// doesn't define it. Same value next.config.ts uses for
// withSentryConfig + the Next env block — keeps source-map upload
// keyed on the same string the runtime tags events with.
const { version } = JSON.parse(await readFile("./package.json", "utf-8")) as { version: string };
const sentryRelease = `vigario-technology-solutions@${version}`;

await build({
  entryPoints: ["server.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node24",
  outfile,
  // Native + Next + @sentry/* stay external. The artifact's
  // node_modules/ ships them at runtime; no reason to inline them
  // and double the bundle size.
  external: ["next", "next/*", "@sentry/*", "better-sqlite3"],
  define: {
    "process.env.SENTRY_RELEASE": JSON.stringify(sentryRelease),
  },
  banner: {
    js: [
      `// GENERATED by scripts/build-server.ts — edit server.ts, not this file.`,
      `import { createRequire } from "module";`,
      `const require = createRequire(import.meta.url);`,
    ].join("\n"),
  },
  logLevel: "info",
});

// --check smoke: catches ERR_MODULE_NOT_FOUND at build time. The
// real-boot smoke in postbuild.ts catches the rest (boot path,
// listen, shutdown).
const probe = spawnSync(process.execPath, [outfile, "--check"], {
  stdio: "inherit",
  env: { ...process.env, SQLITE_PATH: "", SENTRY_DSN: "" },
});
if (probe.status !== 0) {
  console.error(`[build-server] --check failed (exit ${probe.status})`);
  process.exit(1);
}
